# Generated by Django 4.1.2 on 2022-10-18 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100, unique=True, verbose_name='VIN')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('price', models.IntegerField(verbose_name='Цена (руб)')),
                ('model_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1899), django.core.validators.MaxValueValidator(2022)])),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
